Models/ContatoModel.cs
using contrleCarro.Data;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace contrleCarro.Models
{
    public class ContatoModel
    {
        [Key()]
        public int Id { get; set; }

        public string Modelo { get; set; }

        public string Cor { get; set; }

        public string Placa { get; set; }

       
        [ForeignKey("MarcaModel")]
        public int MarcaId { get; set; }
        public virtual MarcaModel Marca { get; set; }

       
    }
}

Models/ErrorViewModel.cs
using System;

namespace contrleCarro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/MarcaModel.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Threading.Tasks;

namespace contrleCarro.Models
{
    public class MarcaModel
    {
        public MarcaModel()
        {
            ContatoModel = new Collection<ContatoModel>(); 
        }

        public int Id { get; set; }

        public string Marca { get; set; }

        public virtual ICollection<ContatoModel> ContatoModel { get; set; }
    }
      
}

Controllers/ContatoController.cs
using contrleCarro.Models;
using contrleCarro.Repositorio;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace contrleCarro.Controllers
{
    public class ContatoController : Controller
    {
        private readonly IContatoRepositorio _contatoRepositorio;

        public ContatoController(IContatoRepositorio contatoRepositorio)
        {
            _contatoRepositorio = contatoRepositorio;
        }

        public IActionResult Index()
        {
            List<ContatoModel> contatos = _contatoRepositorio.BuscarTodos();

            return View(contatos);
        }

        public IActionResult Criar()
        {
            return View();
        }

        public IActionResult Editar(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListaPorId(id);
            return View(contato);
        }

        public IActionResult ApagarConfirmacao(int id)
        {
            ContatoModel contato = _contatoRepositorio.ListaPorId(id);
            return View(contato);
        }

        public IActionResult Apagar(int id)
        {
            _contatoRepositorio.Apagar(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Criar(ContatoModel contato)
        {
            _contatoRepositorio.Adicionar(contato);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Alterar(ContatoModel contato)
        {
            _contatoRepositorio.Atualizar(contato);
            return RedirectToAction("Index");
        }
    }
}

Controllers/HomeController.cs
using contrleCarro.Models;
using contrleCarro.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace contrleCarro.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

             
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
              
    }
}

Controllers/MarcaController.cs
using contrleCarro.Models;
using contrleCarro.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace contrleCarro.Controllers
{
    public class MarcaController : Controller
    {
        private readonly IMarcaRepositorio _marcaRepositorio;

        public MarcaController(IMarcaRepositorio marcaRepositorio)
        {
            _marcaRepositorio = marcaRepositorio;
        }

        public IActionResult Index()
        {
            List<MarcaModel> marca = _marcaRepositorio.BuscarTodos();
            

            return View(marca);
        }

        public IActionResult CriarMarcas()
        {
            
            
            return View();
        }
        
        [HttpPost]
        public IActionResult CriarMarcas(MarcaModel contato)
        {
            _marcaRepositorio.Adicionar(contato);
            return RedirectToAction("Index");
        }
    }
}

Views/Contato/ApagarConfirmacao.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Apagar Modelo";
}

<div class="text-center">
    <h3>Realmente deseja apagar este modelo (@Model.Modelo)?</h3>
</div>

<a class="btn btn-primary btn-block" role="button" asp-controller="Contato" asp-action="Index">Cancelar Exclusão</a>
<a class="btn btn-danger btn-block" role="button" asp-route-id="@Model.Id" asp-controller="Contato" asp-action="Apagar">Confirmar Exclusão</a>

Views/Contato/Criar.cshtml
@model ContatoModel
@{ 
    ViewData["Title"] = "Criar Modelo";
}


<div class="text-center">

    <h1 class="display-4"> Adicionar novo Modelo</h1>

</div>

<form asp-controller="Contato" asp-action="Criar" method="post">
    <div class="form-group">
        <label for="Modelo">Modelo</label>
        <input type="text" asp-for="Modelo" class="form-control" placeholder="Digite o Modelo">
    </div>

    <div class="form-group">
        <label for="Cor">Cor</label>
        <select class="form-select" asp-for="Cor">
            <option>Selecione a Cor</option>
            <option value="AZUL">AZUL</option>
            <option value="PRETO">PRETO</option>
            <option value="VERMELHO">VERMELHO</option>
            <option value="BRANCO">BRANCO</option>
        </select>
    </div>

    
    <div class="form-group">
        <label for="Placa">Placa</label>
        <input type="text" asp-for="Placa" class="form-control" placeholder="Digite a Placa">
    </div>


    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Views/Contato/Editar.cshtml
@model ContatoModel
@{
    ViewData["Title"] = "Editar Modelo";
}


<div class="text-center">


    <h1 class="display-4"> Editar Modelo</h1>

</div>

<form asp-controller="Contato" asp-action="Alterar" method="post">
    
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label for="Modelo">Modelo</label>
        <input type="text" asp-for="Modelo" class="form-control" placeholder="Digite o Modelo">
    </div>

    <div class="form-group">
        <label for="Cor">Cor</label>
        <select class="form-select" asp-for="Cor">
            <option>Selecione a Cor</option>
            <option value="AZUL">AZUL</option>
            <option value="PRETO">PRETO</option>
            <option value="VERMELHO">VERMELHO</option>
            <option value="BRANCO">BRANCO</option>
        </select>
    </div>


    <div class="form-group">
        <label for="Placa">Placa</label>
        <input type="text" asp-for="Placa" class="form-control" placeholder="Digite a Placa">
    </div>


    <button type="submit" class="btn btn-primary">Alterar</button>
    <a class="btn btn-secondary" asp-controller="Contato" asp-action="Index" role="button">Voltar</a>
</form>

Views/Contato/Index.cshtml
@model List<ContatoModel>
@{
    ViewData["Title"] = "Listagem por Modelo";
}

<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-action="Criar" asp-controller="Contato">Adicionar novo Modelo</a>
    </div>
    
    <br />
    
    <h1 class="display-4"> Lista de Modelo</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Modelo</th>
                <th scope="col">Cor</th>
                <th scope="col">Placa</th>


            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (ContatoModel contato in Model)
                {
                    <tr>
                        <th scope="row">@contato.Id</th>
                        <td>@contato.Modelo</td>
                        <td>@contato.Cor</td>
                        <td>@contato.Placa</td>
                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary" asp-route-id="@contato.Id" asp-controller="Contato" asp-action="Editar">Editar</a>
                                <a role="button" class="btn btn-danger"  asp-route-id="@contato.Id"  asp-controller="Contato" asp-action="ApagarConfirmacao">Excluir</a>
                            </div>
                        </td>

                    </tr>

                }
            }


        </tbody>
    </table>
    <br />
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-action="Index" asp-controller="Marca">Voltar</a>
    </div>

</div>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Página Inicial";
}

<div class="text-center">
    <h1 class="display-4">Bem Vindo</h1>
    <p>Lava Jato dos Irmãos</p>
        
</div>

<br />
<br />
<br />
<br />

<div class="text-center">
    <a class="btn btn-primary" role="button" asp-action="Index" asp-controller="Marca">Entrar</a>
</div>

Views/Marca/CriarMarcas.cshtml
@model MarcaModel
@{
    ViewData["Title"] = "Criar Marca";
}


<div class="text-center">

    <h1 class="display-4"> Adicionar nova Marca</h1>

</div>

<form asp-controller="Marca" asp-action="CriarMarcas" method="post">
    <div class="form-group">
        <label for="Marca">Marca</label>
        <input type="text" asp-for="Marca" class="form-control" placeholder="Digite a Marca">
    </div>


    <button type="submit" class="btn btn-primary">Adicionar</button>
    <a class="btn btn-secondary" asp-controller="Marca" asp-action="Index" role="button">Voltar</a>
</form>

Views/Marca/Index.cshtml
@model List<MarcaModel>
@{
    ViewData["Title"] = "Inicial";
}


<div class="text-center">

    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-controller="Marca" asp-action="CriarMarcas">Adicionar nova Marca</a>
    </div>

    <br />

    <h1 class="display-4"> Lista de Marcas</h1>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Marcas</th>

            </tr>
        </thead>
        <tbody>
            @if (Model != null && Model.Any())
            {
                foreach (MarcaModel marca in Model)
                {
                    <tr>
                        <th scope="row">@marca.Id</th>
                        <td>@marca.Marca</td>

                        <td>
                            <div class="btn-group" role="group">
                                <a role="button" class="btn btn-primary"  asp-controller="Contato" asp-action="Index">Entrar</a>

                            </div>
                        </td>

                    </tr>

                }
            }

        </tbody>
    </table>
    <div class="d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary" role="button" asp-action="Index" asp-controller="Home">Sair</a>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Controle de Carros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Controle de Carros</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Pagina Pricipal</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Marca" asp-action="Index">Marca Carros</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contato" asp-action="Index">Modelo Carros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Controle de Carros 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>